[package]
name = "boolenum"
version = "0.1.0"
authors = ["sean billig <sean.billig@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.31"
quote = "1.0.7"
proc-macro-error = "1.0.2"

[dev-dependencies]
trybuild = "1.0.30"
